Hotfix/ss 419
lunasoft/sw-sdk-visual-delphi pull request #11
Opened 2023-10-20 15:28 UTC by martinfnsw

2023-10-20 16:48 UTC, SebastianSW approved these changes

2023-10-20 18:53 UTC, ReyesSW requested changes
En el tema de cancelación manda un error en el form.

2023-10-23 22:09 UTC, ReyesSW approved these changes

2023-10-23 22:17 UTC, FerCarrilloM approved these changes

2023-10-23 22:19 UTC, marifersw approved these changes

2023-10-23 22:22 UTC, SwAeyrton approved these changes

2023-10-23 22:28 UTC, merged