Update Readme
lunasoft/sw-sdk-visual-delphi pull request #13
Opened 2024-02-13 16:47 UTC by martinfnsw

2024-02-13 22:15 UTC, SwAeyrton reviewed
no estoy seguro donde se sube la version de esta libreria

2024-02-13 22:15 UTC, SwAeyrton commented on README.md
> +  StampResponse := Stamp.StampVa(url, token, xml);
Error ortografico

2024-02-13 22:19 UTC, martinfnsw commented
> no estoy seguro donde se sube la version de esta libreria

Estuve buscándolo y tampoco lo encontré :/ revisando PR's pasados tampoco se ha actualizado la versión

2024-02-13 22:51 UTC, SwAeyrton approved these changes

2024-02-13 23:05 UTC, FerCarrilloM requested changes

2024-02-13 23:05 UTC, FerCarrilloM commented on README.md
>  ```pascal
Puede que necesite algún salto de línea o un <br>
Porque como que el </summary> hace que no se vea bien el ejemplo:
![image](https://github.com/lunasoft/sw-sdk-visual-delphi/assets/108951984/75d1afa6-4ef0-48ea-bb8e-e92ff07c4762)

2024-02-13 23:05 UTC, FerCarrilloM commented on README.md
>  ```pascal
Puede que necesite algún salto de línea o un <br>
Porque como que el </summary> hace que no se vea bien el ejemplo:

2024-02-13 23:05 UTC, FerCarrilloM commented on README.md
>  ```pascal
Aqui tambien pasa lo mismo con el ejemplo:
![image](https://github.com/lunasoft/sw-sdk-visual-delphi/assets/108951984/fb9d7924-3988-428f-b919-7557212aca2c)

2024-02-13 23:05 UTC, FerCarrilloM commented on README.md
>  Ejemplo de uso
Aquí también se ve raro el ejemplo.
![image](https://github.com/lunasoft/sw-sdk-visual-delphi/assets/108951984/5d6b7fcb-9dfe-44dc-9886-79b5be9313e5)

2024-02-13 23:05 UTC, FerCarrilloM commented on README.md
>  # Consulta de Documentos Relacionados #
Aquí también paso lo de la vista rara de los ejemplos, con todos los métodos, menos el de "Relacionados por UUID"

2024-02-13 23:05 UTC, FerCarrilloM commented on README.md
> +  StampResponse := Stamp.StampVa(url, token, xml);
Creo que se pudo "StampVa" en vez de "StampV1"

2024-02-13 23:50 UTC, FerCarrilloM approved these changes

2024-02-14 00:11 UTC, SebastianSW approved these changes

2024-02-14 15:18 UTC, marifersw approved these changes

2024-02-14 19:37 UTC, merged