Refactorización de la librería, se anexan nuevos metodos de cancelaci…
lunasoft/sw-sdk-visual-delphi pull request #8
Opened 2018-10-02 20:52 UTC by ecs515

Se refactoriza la librería, se agregan nuevos métodos te emisión-timbrado, se serializan los json (como objetos), se agregan nuevos métodos de cancelación.

2018-10-02 21:09 UTC, hermesw reviewed
__history folder son necesarios esos archivos?

2018-10-02 21:09 UTC, hermesw commented on Authentication/__history/Authentication.pas.~82~
> +unit Authentication;
Estos archivos tengo entendido no son necesarios , los del folder __history.

2018-10-02 21:13 UTC, hermesw requested changes

2018-10-02 21:13 UTC, hermesw commented on Cancelation/Cancelation.pas
> +function CancelationAcceptRejectByCsd(URL, Token, RFCEmisor, Uuid, Accion,
Mismo caso otras librerías, hay que separarlos. Aceptar o rechazar es un servicio diferente a Cancelación. Debería ser independiente. ( Otra clase ) .

2018-10-02 21:13 UTC, hermesw commented on Cancelation/Cancelation.pas
> +function CancelationRelationsByUuid(URL, Token, RFCEmisor, Uuid: String)
Separarlos.

2018-10-02 22:40 UTC, hermesw approved these changes

2018-10-02 22:54 UTC, JuanGamezSW approved these changes

2018-11-05 22:51 UTC, alxcodes approved these changes

2018-11-05 23:48 UTC, merged